services:
  # CodeIgniter application service
  ci4app:
    image: edersohe/ci4app
    volumes:
      - ./ci4app:/var/www/html # Mount the local ci4app folder to the container
    environment:
      CI_ENVIRONMENT: "${CI_ENVIRONMENT}"
      app_baseURL: "https://${CI_DOMAIN}"
      database_default_dbdriver: "${DB_DRIVER}"
      database_default_hostname: "${DB_HOST}"
      database_default_database: "${DB_NAME}"
      database_default_username: "${DB_USER}"
      database_default_password: "${DB_PASS}"

  # Caddy server with Mercure enabled
  mercure:
    image: dunglas/mercure
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # Mount the Caddyfile from your project
      - ./ci4app:/var/www/html # Share the same folder with ci4app for static files
      - mercure_data:/data
      - mercure_config:/config
    ports:
      - "80:80"
      - "443:443"
    environment:
      CI_DOMAIN: "${CI_DOMAIN}"                # Set the domain you want to use
      MERCURE_PUBLISHER_JWT: "${MERCURE_PUBLISHER_JWT}"  # Replace with your secret key
      MERCURE_SUBSCRIBER_JWT: "${MERCURE_SUBSCRIBER_JWT}" # Replace with your secret key

  # MySQL database service
  mysql:
    image: mysql:8.4
    volumes:
      - mysql_data:/var/lib/mysql # Store MySQL data in a named volume
    environment:
      MYSQL_ROOT_PASSWORD: "password" # Change this to your root password
      MYSQL_DATABASE: "${DB_NAME}"          # The default database name for your app
      MYSQL_USER: "${DB_USER}"            # The database user
      MYSQL_PASSWORD: "${DB_PASS}"    # The database user password

  # PostgreSQL database service
  postgres:
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql

  # Adminer
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: ${DB_HOST}
      ADMINER_DESIGN: "nette"

# Define named volumes for data persistence
volumes:
  mysql_data:
  postgres_data:
  mercure_data:
  mercure_config:
